name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Generate Lambda ZIP
        run: zip -r lambda_function.zip app

      - name: Copy Lambda ZIP to infra
        run: cp lambda_function.zip infra/lambda_function.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform -chdir="./infra" init

      - name: Terraform Apply
        run: terraform -chdir="./infra" apply -auto-approve

      - name: Deploy Complete
        run: echo "Lambda deployed successfully"